# Generated by Django 3.1.5 on 2021-01-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='address2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='about',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
