# Generated by Django 3.1 on 2021-01-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210110_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='email_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
